server:
  port: 8080
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          'CorsConfig':
            allowedOrigins:
              - http://locaLhost:4200
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - Content-Type
              - Authorization
            allowCredentials: true

      discovery:
        locator:
          enabled: true

      routes:
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
logging:
  level:
    org:
      springframework:
        web: DEBUG

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

